FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN sed -i 's/\r$//' gradlew && chmod +x ./gradlew && ./gradlew dependencies --no-daemon

EXPOSE 8080

CMD ["sh", "-c", "sed -i 's/\\r$//' gradlew && chmod +x ./gradlew && ./gradlew bootRun --no-daemon"]
